# gz topic published by IMU plugin
- ros_topic_name: "imu"
  gz_topic_name: "imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin
- ros_topic_name: "/front_laser/scan"
  gz_topic_name: "/front_laser/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin
- ros_topic_name: "/front_laser/scan/points"
  gz_topic_name: "/front_laser/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin
- ros_topic_name: "/back_laser/scan"
  gz_topic_name: "/back_laser/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin
- ros_topic_name: "/back_laser/scan/points"
  gz_topic_name: "/back_laser/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Camera1 Color)
- ros_topic_name: "/camera1/color/image/info"
  gz_topic_name: "/camera1/color/image/info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Camera1 Color Image)
- ros_topic_name: "/camera1/color/image"
  gz_topic_name: "/camera1/color/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
 
# gz topic published by Sensors plugin (Camera2 Color)
- ros_topic_name: "/camera2/color/image/info"
  gz_topic_name: "/camera2/color/image/info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Camera2 Color Image)
- ros_topic_name: "/camera2/color/image"
  gz_topic_name: "/camera2/color/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Camera1 Infra1)
- ros_topic_name: "/camera1/infra1/image/info"
  gz_topic_name: "/camera1/infra1/image/info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Camera1 Infra1 Image)
- ros_topic_name: "/camera1/infra1/image"
  gz_topic_name: "/camera1/infra1/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
 
# gz topic published by Sensors plugin (Camera2 Infra1)
- ros_topic_name: "/camera2/infra1/image/info"
  gz_topic_name: "/camera2/infra1/image/info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Camera2 Infra1 Image)
- ros_topic_name: "/camera2/infra1/image"
  gz_topic_name: "/camera2/infra1/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

  # gz topic published by Sensors plugin (Camera1 Infra2)
- ros_topic_name: "/camera1/infra2/image/info"
  gz_topic_name: "/camera1/infra2/image/info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Camera1 Infra2 Image)
- ros_topic_name: "/camera1/infra2/image"
  gz_topic_name: "/camera1/infra2/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
 
# gz topic published by Sensors plugin (Camera2 Infra2)
- ros_topic_name: "/camera2/infra2/image/info"
  gz_topic_name: "/camera2/infra2/image/info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Camera2 Infra2 Image)
- ros_topic_name: "/camera2/infra2/image"
  gz_topic_name: "/camera2/infra2/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Camera1 Depth)
- ros_topic_name: "/camera1/depth/camera_info"
  gz_topic_name: "/camera1/depth/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Camera1 Depth Image)
- ros_topic_name: "/camera1/depth/image"
  gz_topic_name: "/camera1/depth/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Camera1 Depth Pointcloud)
- ros_topic_name: "/camera1/depth/image/points"
  gz_topic_name: "/camera1/depth/image/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
 
# gz topic published by Sensors plugin (Camera2 Depth)
- ros_topic_name: "/camera2/depth/camera_info"
  gz_topic_name: "/camera2/depth/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Camera2 Depth Image)
- ros_topic_name: "/camera2/depth/image"
  gz_topic_name: "/camera2/depth/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Camera2 Depth Pointcloud)
- ros_topic_name: "/camera2/depth/image/points"
  gz_topic_name: "/camera2/depth/image/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS